version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - 27018:27017
    volumes:
      - ../docker-volumes/mongo:/data/db
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - ../docker-volumes/redis:/data
        